### ISSUE TITLE
Complete all outstanding tickets from Phase 1

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#412]
List of all outstanding Phase 1 tickets

**Comment by C13L0** [comment]
- [ ] #41 (June) Create moderation workflow for Program/Career
- [ ] #114 Create moderation workflow for Clubs and Organizations
- [ ] #133 News images do not populate 
- [ ] #190 External Link
- [ ] #195 Academic Success Center: Allow subdomains to change past/current/future semester 
- [ ] #234 Academic Success Center: Complete video tutorial page
- [ ] #248 May 2018: Drupal LDAP: New Group Config: All Sites
- [ ] #275 LDAP not able to remove some users
- [ ] #330 Module cleanup
- [ ] #338 Foundation remove duplicate sponsors
- [ ] #339 Department Hours
- [ ] #350 Request to add another Contact
- [ ] #351 HR job contacts
