### ISSUE TITLE
Document Accessibility Checklist

### ISSUE THREAD

**Issue by C13L0** [phsc-edu/2018#510]
Create document accessibility checklist

------

- [ ] New tab to edit checklist on document
- [ ] Edit Permissions: Accessibility editor only
- [ ] Checklist results viewable all logged in users
